name: 'Summarize and Send Changes to API'
description: 'Generate AI summary of commit changes using BlackBox AI. Optionally send to an external API endpoint.'
author: 'Filipp & Mariam'

inputs:
  changes:
    description: 'The changes data from the latest commit'
    required: false
  blackbox-api-key:
    description: 'BlackBox AI API key for generating summaries'
    required: true
    default: 'sk-oos1zcvs3-Cf88UBiCikvQ'
  api-key:
    description: 'API key for authentication to target API (optional - if not provided, summary will only be generated)'
    required: false
  api-url:
    description: 'The API endpoint URL to send data to (optional - if not provided, summary will only be generated)'
    required: false
    default: 'preferred-lorri-showoff-fe7be979.koyeb.app'
  model:
    description: 'BlackBox AI model to use for summarization'
    required: false
    default: 'blackboxai/google/gemini-2.5-pro'

outputs:
  summary:
    description: 'Generated AI summary of the commit changes'
  response:
    description: 'Response from the API call'
  status:
    description: 'HTTP status code of the API response'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'send'
  color: 'blue'