name: Test Summarize and Send Changes to API

on:
  push:
    branches: [ main ]

jobs:
  summarize-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Required for git diff

      - name: Install dependencies
        run: npm install

      - name: Summarize and Send to API
        uses: ./
