name: Test Summarize and Send Changes to API

on:
  push:
    branches: [ main ]

jobs:
  summarize-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Required for git diff

      - name: Summarize and Send to API
        uses: ./
        with:
          blackbox-api-key: ${{ secrets.BLACKBOX_API_KEY }}
          api-key: ${{ secrets.API_KEY }}
          api-url: 'https://your-api.com/changes'  # Replace with your actual API URL
          model: 'blackboxai'
